spring:
  application:
    name: ProjetoPDS
    jackson:
      mapper:
        accept-case-insensitive-enums: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true

jwt:
  secret: 
  expiration: 7200000

logging:
  level:
    com.luccasaps.projetopds: INFO
    org.springframework.security: INFO



geocoding:
  opencage:
    api-key: 
